tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "anyenv"
brew "automake"
brew "libevent"
brew "neovim", args: ["HEAD"]
brew "pkg-config"
brew "zplug"
cask "forklift"
cask "google-chrome"
cask "hammerspoon"
cask "iterm2"
cask "visual-studio-code"
